### ISSUE TITLE
[BUG]: Unable to get output.

### ISSUE THREAD

**Issue by csv610** [iamarunbrahma/vision-parse#5]
### Bug Description

Took long time to process 12 page pdf file on linux and finally produced the following error.

### Steps to Reproduce

just using the code provided on the webpage

### Python Version

3.12

### Error Message

```shell
(pdfenv) % vi visparse.py
(pdfenv) % python visparse.py GoingWithTheFlow.pdf
Converting pages in PDF file into markdown format:  92%|███████████████▌ | 11/12 [06:25<00:35, 35.08s/it]
Traceback (most recent call last):
  File "/media/csverma/M2Disk/Projects/PDFTools/pdfenv/lib/python3.12/site-packages/vision_parse/parser.py", line 118, in convert_pdf
    text = self._convert_page(
           ^^^^^^^^^^^^^^^^^^^
  File "/media/csverma/M2Disk/Projects/PDFTools/pdfenv/lib/python3.12/site-packages/vision_parse/parser.py", line 95, in _convert_page
    return self.llm.generate_markdown(base64_encoded)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/csverma/M2Disk/Projects/PDFTools/pdfenv/lib/python3.12/site-packages/vision_parse/llm.py", line 148, in generate_markdown
    json_response = ImageDescription.model_validate_json(response)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/csverma/M2Disk/Projects/PDFTools/pdfenv/lib/python3.12/site-packages/pydantic/main.py", line 656, in model_validate_json
    return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 2 validation errors for ImageDescription
text_detected
  Field required [type=missing, input_value={'confidence_score_text':...k) + F(gk, Yk+1, tk))."}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
tables_detected
  Field required [type=missing, input_value={'confidence_score_text':...k) + F(gk, Yk+1, tk))."}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/csverma/M2Disk/Projects/PDFTools/visparse.py", line 23, in <module>
    markdown_pages = parser.convert_pdf(pdf_path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/csverma/M2Disk/Projects/PDFTools/pdfenv/lib/python3.12/site-packages/vision_parse/parser.py", line 128, in convert_pdf
    raise VisionParserError(
vision_parse.parser.VisionParserError: Failed to convert PDF file into markdown content: 2 validation errors for ImageDescription
text_detected
  Field required [type=missing, input_value={'confidence_score_text':...k) + F(gk, Yk+1, tk))."}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
tables_detected
  Field required [type=missing, input_value={'confidence_score_text':...k) + F(gk, Yk+1, tk))."}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1735150324.453576  753237 init.cc:229] grpc_wait_for_shutdown_with_timeout() timed out.
(pdfenv) %
```

### Expected Behavior

expected the code to work given on the webpage

**Comment by iamarunbrahma** [comment]
Hello @csv610 ,
This issue has been resolved in the current release. You can use `enable_concurrency` parameter and set it to `True`, to fasten up the pdf processing.
